
package co.manager.b1ws.incomingPayments;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IncomingPaymentsService", targetNamespace = "IncomingPaymentsService", wsdlLocation = "http://192.168.10.102/B1WS/WebReferences/IncomingPaymentsService.wsdl")
public class IncomingPaymentsService
    extends Service
{

    private final static URL INCOMINGPAYMENTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException INCOMINGPAYMENTSSERVICE_EXCEPTION;
    private final static QName INCOMINGPAYMENTSSERVICE_QNAME = new QName("IncomingPaymentsService", "IncomingPaymentsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.102/B1WS/WebReferences/IncomingPaymentsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INCOMINGPAYMENTSSERVICE_WSDL_LOCATION = url;
        INCOMINGPAYMENTSSERVICE_EXCEPTION = e;
    }

    public IncomingPaymentsService(URL url) {
        super(__getWsdlLocation(), INCOMINGPAYMENTSSERVICE_QNAME);
    }

    public IncomingPaymentsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns IncomingPaymentsServiceSoap
     */
    @WebEndpoint(name = "IncomingPaymentsServiceSoap")
    public IncomingPaymentsServiceSoap getIncomingPaymentsServiceSoap() {
        return super.getPort(new QName("IncomingPaymentsService", "IncomingPaymentsServiceSoap"), IncomingPaymentsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IncomingPaymentsServiceSoap
     */
    @WebEndpoint(name = "IncomingPaymentsServiceSoap")
    public IncomingPaymentsServiceSoap getIncomingPaymentsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("IncomingPaymentsService", "IncomingPaymentsServiceSoap"), IncomingPaymentsServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns IncomingPaymentsServiceSoap
     */
    @WebEndpoint(name = "IncomingPaymentsServiceSoap12")
    public IncomingPaymentsServiceSoap getIncomingPaymentsServiceSoap12() {
        return super.getPort(new QName("IncomingPaymentsService", "IncomingPaymentsServiceSoap12"), IncomingPaymentsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IncomingPaymentsServiceSoap
     */
    @WebEndpoint(name = "IncomingPaymentsServiceSoap12")
    public IncomingPaymentsServiceSoap getIncomingPaymentsServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("IncomingPaymentsService", "IncomingPaymentsServiceSoap12"), IncomingPaymentsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INCOMINGPAYMENTSSERVICE_EXCEPTION!= null) {
            throw INCOMINGPAYMENTSSERVICE_EXCEPTION;
        }
        return INCOMINGPAYMENTSSERVICE_WSDL_LOCATION;
    }

}
