
package co.manager.b1ws.state;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140803.1500
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatesServiceSoap", targetNamespace = "StatesService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StatesServiceSoap {


    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.manager.b1ws.client.state.AddStateResponse
     */
    @WebMethod(operationName = "AddState", action = "StatesService/AddState")
    @WebResult(name = "AddStateResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public AddStateResponse addState(
        @WebParam(name = "AddState", targetNamespace = "StatesService", partName = "parameters")
        AddState parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.manager.b1ws.client.state.UpdateStateResponse
     */
    @WebMethod(operationName = "UpdateState", action = "StatesService/UpdateState")
    @WebResult(name = "UpdateStateResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public UpdateStateResponse updateState(
        @WebParam(name = "UpdateState", targetNamespace = "StatesService", partName = "parameters")
        UpdateState parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.manager.b1ws.client.state.DeleteStateResponse
     */
    @WebMethod(operationName = "DeleteState", action = "StatesService/DeleteState")
    @WebResult(name = "DeleteStateResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public DeleteStateResponse deleteState(
        @WebParam(name = "DeleteState", targetNamespace = "StatesService", partName = "parameters")
        DeleteState parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.manager.b1ws.client.state.GetStateResponse
     */
    @WebMethod(operationName = "GetState", action = "StatesService/GetState")
    @WebResult(name = "GetStateResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetStateResponse getState(
        @WebParam(name = "GetState", targetNamespace = "StatesService", partName = "parameters")
        GetState parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.manager.b1ws.client.state.GetStateListResponse
     */
    @WebMethod(operationName = "GetStateList", action = "StatesService/GetStateList")
    @WebResult(name = "GetStateListResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetStateListResponse getStateList(
        @WebParam(name = "GetStateList", targetNamespace = "StatesService", partName = "parameters")
        GetStateList parameters,
        @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
        MsgHeader requestHeader);

}
