
package co.manager.b1ws.businessPartners;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BusinessPartnersService", targetNamespace = "BusinessPartnersService", wsdlLocation = "http://192.168.10.102/B1WS/WebReferences/BusinessPartnersService.wsdl")
public class BusinessPartnersService
    extends Service
{

    private final static URL BUSINESSPARTNERSSERVICE_WSDL_LOCATION;
    private final static WebServiceException BUSINESSPARTNERSSERVICE_EXCEPTION;
    private final static QName BUSINESSPARTNERSSERVICE_QNAME = new QName("BusinessPartnersService", "BusinessPartnersService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.10.102/B1WS/WebReferences/BusinessPartnersService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BUSINESSPARTNERSSERVICE_WSDL_LOCATION = url;
        BUSINESSPARTNERSSERVICE_EXCEPTION = e;
    }

    public BusinessPartnersService(URL url) {
        super(__getWsdlLocation(), BUSINESSPARTNERSSERVICE_QNAME);
    }

    public BusinessPartnersService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns BusinessPartnersServiceSoap
     */
    @WebEndpoint(name = "BusinessPartnersServiceSoap")
    public BusinessPartnersServiceSoap getBusinessPartnersServiceSoap() {
        return super.getPort(new QName("BusinessPartnersService", "BusinessPartnersServiceSoap"), BusinessPartnersServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessPartnersServiceSoap
     */
    @WebEndpoint(name = "BusinessPartnersServiceSoap")
    public BusinessPartnersServiceSoap getBusinessPartnersServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("BusinessPartnersService", "BusinessPartnersServiceSoap"), BusinessPartnersServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns BusinessPartnersServiceSoap
     */
    @WebEndpoint(name = "BusinessPartnersServiceSoap12")
    public BusinessPartnersServiceSoap getBusinessPartnersServiceSoap12() {
        return super.getPort(new QName("BusinessPartnersService", "BusinessPartnersServiceSoap12"), BusinessPartnersServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BusinessPartnersServiceSoap
     */
    @WebEndpoint(name = "BusinessPartnersServiceSoap12")
    public BusinessPartnersServiceSoap getBusinessPartnersServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("BusinessPartnersService", "BusinessPartnersServiceSoap12"), BusinessPartnersServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BUSINESSPARTNERSSERVICE_EXCEPTION!= null) {
            throw BUSINESSPARTNERSSERVICE_EXCEPTION;
        }
        return BUSINESSPARTNERSSERVICE_WSDL_LOCATION;
    }

}
