
package co.manager.b1ws.item;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ItemsServiceSoap", targetNamespace = "ItemsService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemsServiceSoap {


    /**
     * 
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.igb.b1ws.client.item.AddResponse
     */
    @WebMethod(operationName = "Add", action = "ItemsService/Add")
    @WebResult(name = "AddResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public AddResponse add(
            @WebParam(name = "Add", targetNamespace = "ItemsService", partName = "parameters")
                    Add parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
                    MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.igb.b1ws.client.item.GetByParamsResponse
     */
    @WebMethod(operationName = "GetByParams", action = "ItemsService/GetByParams")
    @WebResult(name = "GetByParamsResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public GetByParamsResponse getByParams(
            @WebParam(name = "GetByParams", targetNamespace = "ItemsService", partName = "parameters")
                    GetByParams parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
                    MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.igb.b1ws.client.item.UpdateResponse
     */
    @WebMethod(operationName = "Update", action = "ItemsService/Update")
    @WebResult(name = "UpdateResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public UpdateResponse update(
            @WebParam(name = "Update", targetNamespace = "ItemsService", partName = "parameters")
                    Update parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
                    MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.igb.b1ws.client.item.RemoveResponse
     */
    @WebMethod(operationName = "Remove", action = "ItemsService/Remove")
    @WebResult(name = "RemoveResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public RemoveResponse remove(
            @WebParam(name = "Remove", targetNamespace = "ItemsService", partName = "parameters")
                    Remove parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
                    MsgHeader requestHeader);

    /**
     *
     * @param requestHeader
     * @param parameters
     * @return
     *     returns co.igb.b1ws.client.item.CancelResponse
     */
    @WebMethod(operationName = "Cancel", action = "ItemsService/Cancel")
    @WebResult(name = "CancelResponse", targetNamespace = "http://www.sap.com/SBO/DIS", partName = "parameters")
    public CancelResponse cancel(
            @WebParam(name = "Cancel", targetNamespace = "ItemsService", partName = "parameters")
                    Cancel parameters,
            @WebParam(name = "MsgHeader", targetNamespace = "http://www.sap.com/SBO/DIS", header = true, partName = "request_header")
                    MsgHeader requestHeader);

}
